live_config_reload = true

import = [
   # "~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
   # "~/.config/alacritty/themes/themes/night_owl.toml"
   "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 1
y = 1

[font]
size = 9

[font.bold]
family = "Monoid Nerd Font"
style = "Bold"

[font.italic]
family = "Monoid Nerd Font"
style = "Italic"

[font.normal]
family = "Monoid Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Monoid Nerd Font"
style = "Bold Italic"
